=== zhaofeng-shu33/tech-chores-archive/2016/ProjectNote/GermanData/WordModel.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Dictionary (Language+)>
<!ELEMENT Language (Lemma*)>
<!ELEMENT Lemma (Stichwort,References*, zusammengesetzteWörter,Synonymegruppe,Antonymegruppe,Kollokationen,AllgemeineErläuterungen)>
  <!ELEMENT zusammengesetzteWörter (KompositaCollection,abgeleiteteWörter)>
  <!ELEMENT KompositaCollection (_K|K_)*>
  <!ELEMENT abgeleiteteWörter (hierzu*)>
  <!ELEMENT _K EMPTY>
  <!ELEMENT K_ EMPTY>
  <!ELEMENT hierzu EMPTY>
  <!ELEMENT AllgemeineErläuterungen (Eintrag+)>
  <!ELEMENT Eintrag (Chinesisch,BeispielSammlung)>
  <!ELEMENT Chinesisch EMPTY>
  <!ELEMENT BeispielSammlung (Beispiel*)>
  <!ELEMENT Beispiel (Satz,Übersetzung)>
  <!ELEMENT Satz EMPTY>
  <!ELEMENT Übersetzung EMPTY>
  <!ELEMENT Stichwort EMPTY>
  <!ELEMENT References (reftypegroup*)>
<!ELEMENT reftypegroup (reference*)>
<!ELEMENT reference EMPTY>

  <!ELEMENT Synonymegruppe (Sym*)>  
  <!ELEMENT Sym EMPTY>  
  <!ELEMENT Antonymegruppe (Anm*)>  
  <!ELEMENT Anm EMPTY>  
  <!ELEMENT Kollokationen (K*)>  
  <!ELEMENT K EMPTY>  
  <!ATTLIST Stichwort Einheit CDATA #REQUIRED>
  <!ATTLIST Stichwort Anteil CDATA #REQUIRED>
  <!ATTLIST Stichwort Genus (der|die|das|Plural) #REQUIRED>
  <!ATTLIST Stichwort Pluralform CDATA #REQUIRED>
  <!ATTLIST Stichwort GenitivSingular CDATA #REQUIRED>
  <!ATTLIST _K Wort CDATA #IMPLIED>
  <!ATTLIST K_ Wort CDATA  #IMPLIED>
  <!ATTLIST hierzu category (Substantiv | Adjektiv | Verben) "Substantiv"> <?Substantiv is the default value?>
  <!ATTLIST hierzu hierzu CDATA #IMPLIED>
  <!ATTLIST Sym Synonym CDATA #IMPLIED>
  <!ATTLIST Anm Antonym CDATA #IMPLIED>
  <!ATTLIST K Wort CDATA #IMPLIED>
  <!ATTLIST Chinesisch TE CDATA #IMPLIED>
  <!ATTLIST Satz Satz CDATA #IMPLIED>
  <!ATTLIST Übersetzung TE CDATA #IMPLIED>
  <!ATTLIST Lemma LemmaSign CDATA #REQUIRED>
  <!ATTLIST Dictionary Name CDATA #IMPLIED>
  <!ATTLIST Stichwort category CDATA #REQUIRED>
<!ATTLIST Dictionary Description CDATA #IMPLIED>
<!ATTLIST Dictionary URL CDATA #IMPLIED>
<!ATTLIST Dictionary SoundPath CDATA #IMPLIED>
<!ATTLIST Dictionary id CDATA #IMPLIED>
<!ATTLIST Language Name CDATA #IMPLIED>
<!ATTLIST References id CDATA #IMPLIED>

=== zhaofeng-shu33/tech-chores-archive/2016/ProjectNote/GermanData/exp.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="GerDicStyleSheet.xsl"?>
<!DOCTYPE Dictionary SYSTEM "WordModel.dtd">
<Dictionary>
<Language Name="German">
<Lemma LemmaSign="Arzt">
<Stichwort category="Substantiv" Einheit="5" Anteil="Übungen" Genus="der" Pluralform="Ärzte" GenitivSingular="Arztes"/>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K Wort="Augenarzt"/>
		<_K Wort="Hausarzt"/>
		<_K Wort="Kinderarzt"/>
		<_K Wort="Zahnarzt"/>
		<_K Wort="Tierarzt"/>
		<_K Wort="Schularzt"/>
		<K_ Wort="Arztberuf"/>
		<_K Wort="Arzttermin"/>
	</KompositaCollection>
	<abgeleiteteWörter>
		<hierzu hierzu="Ärztin"/>
		<hierzu hierzu="ärztlich" category="Adjektiv"/>
	</abgeleiteteWörter>
</zusammengesetzteWörter>

<Synonymegruppe>
	<Sym Synonym="Mediziner"/>
	<Sym Synonym="Doktor"/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm Antonym="Kranker"/>
</Antonymegruppe>
<Kollokationen>

<K Wort="der praktische Arzt"/>
<K Wort="der bekannte Arzt"/>
<K Wort="den Arzt rufen"/>
<K Wort="zum Arzt gehen"/>

</Kollokationen>
<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch TE="医生，大夫"/>
		<BeispielSammlung>
			<Beispiel>
				<Satz Satz="Der Arzt hat ihm eine Medizin verschrieben."/>
				<Übersetzung TE="医生给他开了一剂药。"/>
			</Beispiel>
			<Beispiel>
				<Satz Satz="Hoffnung und Freude sind die besten Ärzte."/>
				<Übersetzung TE="希望和快乐是最好的医生。"/>
			</Beispiel>
			<Beispiel>
				<Satz Satz="Er hat vor,Arzt zu sein."/>
				<Übersetzung TE="他打算成为医生"/>
			</Beispiel>
			<Beispiel>
				<Satz Satz="Gegen Sie mit ihm zum Arzt."/>
				<Übersetzung TE="请您和他一起去看医生。"/>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>
</Lemma>
</Language>
</Dictionary>
